/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Prediction {
    deteriorationRate: number;
    maintenanceYear: bigint;
    futureConditionRatings: {
        rating10: number;
        rating20: number;
        rating5: number;
    };
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Infrastructure {
    id: string;
    age: bigint;
    trafficLoadFactor: number;
    name: string;
    structuralConditionRating: number;
    environmentalExposureFactor: number;
    notes: string;
    structureType: StructureType;
    riskLevel: RiskLevel;
    materialType: MaterialType;
    location: {
        latitude: number;
        area: string;
        longitude: number;
    };
    riskScore: number;
}
export interface CityBudgetSummary {
    breakdownByRiskLevel: {
        low: number;
        high: number;
        moderate: number;
    };
    topPriorityStructures: Array<Infrastructure>;
    totalEstimatedBudget: number;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BudgetEstimate {
    urgencyLevel: UrgencyLevel;
    recommendedAction: string;
    estimatedCost: number;
}
export enum MaterialType {
    compositeMaterial = "compositeMaterial",
    concrete = "concrete",
    asphalt = "asphalt",
    steel = "steel"
}
export enum RiskLevel {
    low = "low",
    high = "high",
    moderate = "moderate"
}
export enum StructureType {
    bridge = "bridge",
    road = "road"
}
export enum UrgencyLevel {
    immediateRepair = "immediateRepair",
    monitorOnly = "monitorOnly",
    scheduledMaintenance = "scheduledMaintenance"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addInfrastructure(input: Infrastructure): Promise<void>;
    deleteInfrastructure(id: string): Promise<void>;
    getAllInfrastructure(): Promise<Array<Infrastructure>>;
    getBudgetEstimate(id: string): Promise<BudgetEstimate>;
    getCityBudgetSummary(): Promise<CityBudgetSummary>;
    getInfrastructureById(id: string): Promise<Infrastructure>;
    getPredictions(id: string): Promise<Prediction>;
    updateInfrastructure(id: string, input: Infrastructure): Promise<void>;
}
import type { BudgetEstimate as _BudgetEstimate, CityBudgetSummary as _CityBudgetSummary, Infrastructure as _Infrastructure, MaterialType as _MaterialType, RiskLevel as _RiskLevel, StructureType as _StructureType, UrgencyLevel as _UrgencyLevel, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addInfrastructure(arg0: Infrastructure): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInfrastructure(to_candid_Infrastructure_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInfrastructure(to_candid_Infrastructure_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteInfrastructure(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInfrastructure(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInfrastructure(arg0);
            return result;
        }
    }
    async getAllInfrastructure(): Promise<Array<Infrastructure>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInfrastructure();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInfrastructure();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudgetEstimate(arg0: string): Promise<BudgetEstimate> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetEstimate(arg0);
                return from_candid_BudgetEstimate_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetEstimate(arg0);
            return from_candid_BudgetEstimate_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCityBudgetSummary(): Promise<CityBudgetSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getCityBudgetSummary();
                return from_candid_CityBudgetSummary_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCityBudgetSummary();
            return from_candid_CityBudgetSummary_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInfrastructureById(arg0: string): Promise<Infrastructure> {
        if (this.processError) {
            try {
                const result = await this.actor.getInfrastructureById(arg0);
                return from_candid_Infrastructure_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInfrastructureById(arg0);
            return from_candid_Infrastructure_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPredictions(arg0: string): Promise<Prediction> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictions(arg0);
            return result;
        }
    }
    async updateInfrastructure(arg0: string, arg1: Infrastructure): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInfrastructure(arg0, to_candid_Infrastructure_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInfrastructure(arg0, to_candid_Infrastructure_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BudgetEstimate_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetEstimate): BudgetEstimate {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_CityBudgetSummary_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CityBudgetSummary): CityBudgetSummary {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Infrastructure_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Infrastructure): Infrastructure {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_MaterialType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaterialType): MaterialType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_StructureType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StructureType): StructureType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UrgencyLevel_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UrgencyLevel): UrgencyLevel {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    trafficLoadFactor: number;
    name: string;
    structuralConditionRating: number;
    environmentalExposureFactor: number;
    notes: string;
    structureType: _StructureType;
    riskLevel: _RiskLevel;
    materialType: _MaterialType;
    location: {
        latitude: number;
        area: string;
        longitude: number;
    };
    riskScore: number;
}): {
    id: string;
    age: bigint;
    trafficLoadFactor: number;
    name: string;
    structuralConditionRating: number;
    environmentalExposureFactor: number;
    notes: string;
    structureType: StructureType;
    riskLevel: RiskLevel;
    materialType: MaterialType;
    location: {
        latitude: number;
        area: string;
        longitude: number;
    };
    riskScore: number;
} {
    return {
        id: value.id,
        age: value.age,
        trafficLoadFactor: value.trafficLoadFactor,
        name: value.name,
        structuralConditionRating: value.structuralConditionRating,
        environmentalExposureFactor: value.environmentalExposureFactor,
        notes: value.notes,
        structureType: from_candid_StructureType_n19(_uploadFile, _downloadFile, value.structureType),
        riskLevel: from_candid_RiskLevel_n21(_uploadFile, _downloadFile, value.riskLevel),
        materialType: from_candid_MaterialType_n23(_uploadFile, _downloadFile, value.materialType),
        location: value.location,
        riskScore: value.riskScore
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    urgencyLevel: _UrgencyLevel;
    recommendedAction: string;
    estimatedCost: number;
}): {
    urgencyLevel: UrgencyLevel;
    recommendedAction: string;
    estimatedCost: number;
} {
    return {
        urgencyLevel: from_candid_UrgencyLevel_n27(_uploadFile, _downloadFile, value.urgencyLevel),
        recommendedAction: value.recommendedAction,
        estimatedCost: value.estimatedCost
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    breakdownByRiskLevel: {
        low: number;
        high: number;
        moderate: number;
    };
    topPriorityStructures: Array<_Infrastructure>;
    totalEstimatedBudget: number;
}): {
    breakdownByRiskLevel: {
        low: number;
        high: number;
        moderate: number;
    };
    topPriorityStructures: Array<Infrastructure>;
    totalEstimatedBudget: number;
} {
    return {
        breakdownByRiskLevel: value.breakdownByRiskLevel,
        topPriorityStructures: from_candid_vec_n16(_uploadFile, _downloadFile, value.topPriorityStructures),
        totalEstimatedBudget: value.totalEstimatedBudget
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bridge: null;
} | {
    road: null;
}): StructureType {
    return "bridge" in value ? StructureType.bridge : "road" in value ? StructureType.road : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    moderate: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "moderate" in value ? RiskLevel.moderate : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    compositeMaterial: null;
} | {
    concrete: null;
} | {
    asphalt: null;
} | {
    steel: null;
}): MaterialType {
    return "compositeMaterial" in value ? MaterialType.compositeMaterial : "concrete" in value ? MaterialType.concrete : "asphalt" in value ? MaterialType.asphalt : "steel" in value ? MaterialType.steel : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    immediateRepair: null;
} | {
    monitorOnly: null;
} | {
    scheduledMaintenance: null;
}): UrgencyLevel {
    return "immediateRepair" in value ? UrgencyLevel.immediateRepair : "monitorOnly" in value ? UrgencyLevel.monitorOnly : "scheduledMaintenance" in value ? UrgencyLevel.scheduledMaintenance : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Infrastructure>): Array<Infrastructure> {
    return value.map((x)=>from_candid_Infrastructure_n17(_uploadFile, _downloadFile, x));
}
function to_candid_Infrastructure_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Infrastructure): _Infrastructure {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_MaterialType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaterialType): _MaterialType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_RiskLevel_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_StructureType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StructureType): _StructureType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    trafficLoadFactor: number;
    name: string;
    structuralConditionRating: number;
    environmentalExposureFactor: number;
    notes: string;
    structureType: StructureType;
    riskLevel: RiskLevel;
    materialType: MaterialType;
    location: {
        latitude: number;
        area: string;
        longitude: number;
    };
    riskScore: number;
}): {
    id: string;
    age: bigint;
    trafficLoadFactor: number;
    name: string;
    structuralConditionRating: number;
    environmentalExposureFactor: number;
    notes: string;
    structureType: _StructureType;
    riskLevel: _RiskLevel;
    materialType: _MaterialType;
    location: {
        latitude: number;
        area: string;
        longitude: number;
    };
    riskScore: number;
} {
    return {
        id: value.id,
        age: value.age,
        trafficLoadFactor: value.trafficLoadFactor,
        name: value.name,
        structuralConditionRating: value.structuralConditionRating,
        environmentalExposureFactor: value.environmentalExposureFactor,
        notes: value.notes,
        structureType: to_candid_StructureType_n10(_uploadFile, _downloadFile, value.structureType),
        riskLevel: to_candid_RiskLevel_n12(_uploadFile, _downloadFile, value.riskLevel),
        materialType: to_candid_MaterialType_n14(_uploadFile, _downloadFile, value.materialType),
        location: value.location,
        riskScore: value.riskScore
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StructureType): {
    bridge: null;
} | {
    road: null;
} {
    return value == StructureType.bridge ? {
        bridge: null
    } : value == StructureType.road ? {
        road: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): {
    low: null;
} | {
    high: null;
} | {
    moderate: null;
} {
    return value == RiskLevel.low ? {
        low: null
    } : value == RiskLevel.high ? {
        high: null
    } : value == RiskLevel.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaterialType): {
    compositeMaterial: null;
} | {
    concrete: null;
} | {
    asphalt: null;
} | {
    steel: null;
} {
    return value == MaterialType.compositeMaterial ? {
        compositeMaterial: null
    } : value == MaterialType.concrete ? {
        concrete: null
    } : value == MaterialType.asphalt ? {
        asphalt: null
    } : value == MaterialType.steel ? {
        steel: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
