/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BudgetEstimate {
  'urgencyLevel' : UrgencyLevel,
  'recommendedAction' : string,
  'estimatedCost' : number,
}
export interface CityBudgetSummary {
  'breakdownByRiskLevel' : {
    'low' : number,
    'high' : number,
    'moderate' : number,
  },
  'topPriorityStructures' : Array<Infrastructure>,
  'totalEstimatedBudget' : number,
}
export interface Infrastructure {
  'id' : string,
  'age' : bigint,
  'trafficLoadFactor' : number,
  'name' : string,
  'structuralConditionRating' : number,
  'photoBase64' : [] | [string],
  'environmentalExposureFactor' : number,
  'notes' : string,
  'structureType' : StructureType,
  'riskLevel' : RiskLevel,
  'materialType' : MaterialType,
  'location' : { 'latitude' : number, 'area' : string, 'longitude' : number },
  'riskScore' : number,
}
export interface InfrastructureInput {
  'id' : string,
  'age' : bigint,
  'trafficLoadFactor' : number,
  'name' : string,
  'structuralConditionRating' : number,
  'photoBase64' : [] | [string],
  'environmentalExposureFactor' : number,
  'notes' : string,
  'structureType' : StructureType,
  'materialType' : MaterialType,
  'location' : { 'latitude' : number, 'area' : string, 'longitude' : number },
}
export type MaterialType = { 'compositeMaterial' : null } |
  { 'concrete' : null } |
  { 'asphalt' : null } |
  { 'steel' : null };
export interface Prediction {
  'deteriorationRate' : number,
  'maintenanceYear' : bigint,
  'futureConditionRatings' : {
    'rating10' : number,
    'rating20' : number,
    'rating5' : number,
  },
}
export interface PredictionResult {
  'deteriorationRate' : number,
  'maintenanceYear' : bigint,
  'budgetEstimate' : BudgetEstimate,
  'riskLevel' : RiskLevel,
  'riskScore' : number,
}
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'moderate' : null };
export type StructureType = { 'bridge' : null } |
  { 'road' : null };
export type UrgencyLevel = { 'immediateRepair' : null } |
  { 'monitorOnly' : null } |
  { 'scheduledMaintenance' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInfrastructure' : ActorMethod<[InfrastructureInput], undefined>,
  'analyzeAndPredict' : ActorMethod<[InfrastructureInput], PredictionResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteInfrastructure' : ActorMethod<[string], undefined>,
  'getAllInfrastructure' : ActorMethod<[], Array<Infrastructure>>,
  'getBudgetEstimate' : ActorMethod<[string], BudgetEstimate>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCityBudgetSummary' : ActorMethod<[], CityBudgetSummary>,
  'getInfrastructureById' : ActorMethod<[string], Infrastructure>,
  'getPredictions' : ActorMethod<[string], Prediction>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInfrastructure' : ActorMethod<
    [string, InfrastructureInput],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];