/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const StructureType = IDL.Variant({
  'bridge' : IDL.Null,
  'road' : IDL.Null,
});
export const MaterialType = IDL.Variant({
  'compositeMaterial' : IDL.Null,
  'concrete' : IDL.Null,
  'asphalt' : IDL.Null,
  'steel' : IDL.Null,
});
export const InfrastructureInput = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'trafficLoadFactor' : IDL.Float64,
  'name' : IDL.Text,
  'structuralConditionRating' : IDL.Float64,
  'photoBase64' : IDL.Opt(IDL.Text),
  'environmentalExposureFactor' : IDL.Float64,
  'notes' : IDL.Text,
  'structureType' : StructureType,
  'materialType' : MaterialType,
  'location' : IDL.Record({
    'latitude' : IDL.Float64,
    'area' : IDL.Text,
    'longitude' : IDL.Float64,
  }),
});
export const UrgencyLevel = IDL.Variant({
  'immediateRepair' : IDL.Null,
  'monitorOnly' : IDL.Null,
  'scheduledMaintenance' : IDL.Null,
});
export const BudgetEstimate = IDL.Record({
  'urgencyLevel' : UrgencyLevel,
  'recommendedAction' : IDL.Text,
  'estimatedCost' : IDL.Float64,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'moderate' : IDL.Null,
});
export const PredictionResult = IDL.Record({
  'deteriorationRate' : IDL.Float64,
  'maintenanceYear' : IDL.Nat,
  'budgetEstimate' : BudgetEstimate,
  'riskLevel' : RiskLevel,
  'riskScore' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Infrastructure = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'trafficLoadFactor' : IDL.Float64,
  'name' : IDL.Text,
  'structuralConditionRating' : IDL.Float64,
  'photoBase64' : IDL.Opt(IDL.Text),
  'environmentalExposureFactor' : IDL.Float64,
  'notes' : IDL.Text,
  'structureType' : StructureType,
  'riskLevel' : RiskLevel,
  'materialType' : MaterialType,
  'location' : IDL.Record({
    'latitude' : IDL.Float64,
    'area' : IDL.Text,
    'longitude' : IDL.Float64,
  }),
  'riskScore' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CityBudgetSummary = IDL.Record({
  'breakdownByRiskLevel' : IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'moderate' : IDL.Float64,
  }),
  'topPriorityStructures' : IDL.Vec(Infrastructure),
  'totalEstimatedBudget' : IDL.Float64,
});
export const Prediction = IDL.Record({
  'deteriorationRate' : IDL.Float64,
  'maintenanceYear' : IDL.Nat,
  'futureConditionRatings' : IDL.Record({
    'rating10' : IDL.Float64,
    'rating20' : IDL.Float64,
    'rating5' : IDL.Float64,
  }),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInfrastructure' : IDL.Func([InfrastructureInput], [], []),
  'analyzeAndPredict' : IDL.Func(
      [InfrastructureInput],
      [PredictionResult],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteInfrastructure' : IDL.Func([IDL.Text], [], []),
  'getAllInfrastructure' : IDL.Func([], [IDL.Vec(Infrastructure)], ['query']),
  'getBudgetEstimate' : IDL.Func([IDL.Text], [BudgetEstimate], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCityBudgetSummary' : IDL.Func([], [CityBudgetSummary], ['query']),
  'getInfrastructureById' : IDL.Func([IDL.Text], [Infrastructure], ['query']),
  'getPredictions' : IDL.Func([IDL.Text], [Prediction], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInfrastructure' : IDL.Func([IDL.Text, InfrastructureInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const StructureType = IDL.Variant({ 'bridge' : IDL.Null, 'road' : IDL.Null });
  const MaterialType = IDL.Variant({
    'compositeMaterial' : IDL.Null,
    'concrete' : IDL.Null,
    'asphalt' : IDL.Null,
    'steel' : IDL.Null,
  });
  const InfrastructureInput = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'trafficLoadFactor' : IDL.Float64,
    'name' : IDL.Text,
    'structuralConditionRating' : IDL.Float64,
    'photoBase64' : IDL.Opt(IDL.Text),
    'environmentalExposureFactor' : IDL.Float64,
    'notes' : IDL.Text,
    'structureType' : StructureType,
    'materialType' : MaterialType,
    'location' : IDL.Record({
      'latitude' : IDL.Float64,
      'area' : IDL.Text,
      'longitude' : IDL.Float64,
    }),
  });
  const UrgencyLevel = IDL.Variant({
    'immediateRepair' : IDL.Null,
    'monitorOnly' : IDL.Null,
    'scheduledMaintenance' : IDL.Null,
  });
  const BudgetEstimate = IDL.Record({
    'urgencyLevel' : UrgencyLevel,
    'recommendedAction' : IDL.Text,
    'estimatedCost' : IDL.Float64,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const PredictionResult = IDL.Record({
    'deteriorationRate' : IDL.Float64,
    'maintenanceYear' : IDL.Nat,
    'budgetEstimate' : BudgetEstimate,
    'riskLevel' : RiskLevel,
    'riskScore' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Infrastructure = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'trafficLoadFactor' : IDL.Float64,
    'name' : IDL.Text,
    'structuralConditionRating' : IDL.Float64,
    'photoBase64' : IDL.Opt(IDL.Text),
    'environmentalExposureFactor' : IDL.Float64,
    'notes' : IDL.Text,
    'structureType' : StructureType,
    'riskLevel' : RiskLevel,
    'materialType' : MaterialType,
    'location' : IDL.Record({
      'latitude' : IDL.Float64,
      'area' : IDL.Text,
      'longitude' : IDL.Float64,
    }),
    'riskScore' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CityBudgetSummary = IDL.Record({
    'breakdownByRiskLevel' : IDL.Record({
      'low' : IDL.Float64,
      'high' : IDL.Float64,
      'moderate' : IDL.Float64,
    }),
    'topPriorityStructures' : IDL.Vec(Infrastructure),
    'totalEstimatedBudget' : IDL.Float64,
  });
  const Prediction = IDL.Record({
    'deteriorationRate' : IDL.Float64,
    'maintenanceYear' : IDL.Nat,
    'futureConditionRatings' : IDL.Record({
      'rating10' : IDL.Float64,
      'rating20' : IDL.Float64,
      'rating5' : IDL.Float64,
    }),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInfrastructure' : IDL.Func([InfrastructureInput], [], []),
    'analyzeAndPredict' : IDL.Func(
        [InfrastructureInput],
        [PredictionResult],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteInfrastructure' : IDL.Func([IDL.Text], [], []),
    'getAllInfrastructure' : IDL.Func([], [IDL.Vec(Infrastructure)], ['query']),
    'getBudgetEstimate' : IDL.Func([IDL.Text], [BudgetEstimate], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCityBudgetSummary' : IDL.Func([], [CityBudgetSummary], ['query']),
    'getInfrastructureById' : IDL.Func([IDL.Text], [Infrastructure], ['query']),
    'getPredictions' : IDL.Func([IDL.Text], [Prediction], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInfrastructure' : IDL.Func([IDL.Text, InfrastructureInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };